# Generated by Django 3.0.5 on 2020-04-27 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_hex', models.CharField(max_length=6)),
                ('color_name', models.CharField(max_length=20)),
                ('color_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('color_name',),
            },
        ),
        migrations.CreateModel(
            name='UserColor',
            fields=[
                ('color_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Color')),
                ('color_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.color',),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=140)),
                ('plan_slug', models.SlugField(max_length=140)),
                ('plan_description', models.CharField(blank=True, max_length=200, null=True)),
                ('plan_version', models.PositiveSmallIntegerField()),
                ('plan_type', models.PositiveIntegerField(choices=[(0, 'Graph view of plan'), (1, 'Table view of plan')])),
                ('plan_date_creation', models.DateTimeField(auto_now_add=True)),
                ('plan_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'unique_together': {('plan_author', 'plan_slug', 'plan_version')},
            },
            managers=[
                ('table_plan_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
