# Generated by Django 3.0.5 on 2020-05-15 16:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200515_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_hex',
            new_name='hex',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_date_creation',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_version',
            new_name='version',
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('author', 'slug', 'version')},
        ),
    ]
