# Generated by Django 3.0.5 on 2020-06-07 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200607_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='author',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='color',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Base color'), (1, 'User color')], default=0),
        ),
    ]
