# Generated by Django 3.0.5 on 2020-06-07 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200607_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='color',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Base color'), (1, 'User color')]),
        ),
    ]
