# Generated by Django 3.0.7 on 2020-06-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200607_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
