# Generated by Django 3.0.5 on 2020-04-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_object_name', models.CharField(max_length=50)),
                ('plan_object_priority', models.PositiveIntegerField()),
                ('plan_object_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Color')),
                ('related_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_vertex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_vertex', to='graph.Vertex')),
                ('start_vertex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_vertex', to='graph.Vertex')),
            ],
        ),
    ]
