# Generated by Django 3.0.5 on 2020-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertex',
            name='plan_object_priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
