# Generated by Django 3.0.5 on 2020-06-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_edge_library_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='library_id',
            field=models.CharField(max_length=200),
        ),
    ]
