# Generated by Django 3.0.7 on 2020-06-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20200603_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertex',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
