# Generated by Django 3.0.7 on 2020-06-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_vertex_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertex',
            name='last_update',
        ),
    ]
