# Generated by Django 3.0.7 on 2020-06-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20200515_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
