# Generated by Django 3.0.7 on 2020-06-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_remove_cell_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
